# Generated by Django 3.2.8 on 2021-10-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_trademarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('detail', models.CharField(max_length=500, verbose_name='Detalle')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.categories', verbose_name='Categoria')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.trademarks', verbose_name='Marca')),
            ],
        ),
    ]
